/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBackupRouteImport } from './routes/_app/backup'
import { Route as AppCatalogueRouteImport } from './routes/_app/catalogue'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers.$customerId'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices.$invoiceId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices.new'
import { Route as AppQuotationsIndexRouteImport } from './routes/_app/quotations.index'
import { Route as AppQuotationsQuotationIdRouteImport } from './routes/_app/quotations.$quotationId'
import { Route as AppQuotationsNewRouteImport } from './routes/_app/quotations.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsIndexRoute = AppQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsQuotationIdRoute =
  AppQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuotationsNewRoute = AppQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/backup': typeof AppBackupRoute
  '/catalogue': typeof AppCatalogueRoute
  '/documents': typeof AppDocumentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/quotations/$quotationId': typeof AppQuotationsQuotationIdRoute
  '/quotations/new': typeof AppQuotationsNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/quotations/': typeof AppQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/backup': typeof AppBackupRoute
  '/catalogue': typeof AppCatalogueRoute
  '/documents': typeof AppDocumentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/quotations/$quotationId': typeof AppQuotationsQuotationIdRoute
  '/quotations/new': typeof AppQuotationsNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/quotations': typeof AppQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/backup': typeof AppBackupRoute
  '/_app/catalogue': typeof AppCatalogueRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/quotations/$quotationId': typeof AppQuotationsQuotationIdRoute
  '/_app/quotations/new': typeof AppQuotationsNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/quotations/': typeof AppQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/catalogue'
    | '/documents'
    | '/reports'
    | '/settings'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/customers/'
    | '/invoices/'
    | '/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/backup'
    | '/catalogue'
    | '/documents'
    | '/reports'
    | '/settings'
    | '/'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/quotations/$quotationId'
    | '/quotations/new'
    | '/customers'
    | '/invoices'
    | '/quotations'
  id:
    | '__root__'
    | '/_app'
    | '/_app/backup'
    | '/_app/catalogue'
    | '/_app/documents'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/'
    | '/_app/customers/$customerId'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/quotations/$quotationId'
    | '/_app/quotations/new'
    | '/_app/customers/'
    | '/_app/invoices/'
    | '/_app/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue': {
      id: '/_app/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/': {
      id: '/_app/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AppQuotationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/$quotationId': {
      id: '/_app/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AppQuotationsQuotationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations/new': {
      id: '/_app/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AppQuotationsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBackupRoute: typeof AppBackupRoute
  AppCatalogueRoute: typeof AppCatalogueRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppQuotationsQuotationIdRoute: typeof AppQuotationsQuotationIdRoute
  AppQuotationsNewRoute: typeof AppQuotationsNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppQuotationsIndexRoute: typeof AppQuotationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupRoute: AppBackupRoute,
  AppCatalogueRoute: AppCatalogueRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppQuotationsQuotationIdRoute: AppQuotationsQuotationIdRoute,
  AppQuotationsNewRoute: AppQuotationsNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppQuotationsIndexRoute: AppQuotationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
